### ISSUE TITLE
Can't transform VFM Sky due to brush imported

### ISSUE THREAD

**Issue by DoradoOroOro** [lasa01/Plumber#123]
**Describe the bug**
The map brush and the 3d sky brush are the same when imported, causing that if you pick the sky and transform it, your map brush will be displaced and upscaled.

**To Reproduce**
1. Import a map
2. Pick the entire 3D sky and use the "Transform 3d VMF sky" option from "Object"
3. See error

**Expected behavior**
The map brush should be separated from the sky brush so when you transform the sky you get the map right

**Related files**
Example files:
[mapas.zip](https://github.com/lasa01/io_import_vmf/files/8883654/mapas.zip)

**Screenshots**
![Captura de pantalla (66)](https://user-images.githubusercontent.com/61947114/173183882-66bdd18c-a2c1-4ff6-8039-8e5cc168623d.png)
![Captura de pantalla (67)](https://user-images.githubusercontent.com/61947114/173183883-37d2d195-157a-4a96-85e7-ddccfa1c7710.png)
![Captura de pantalla (69)](https://user-images.githubusercontent.com/61947114/173183884-982506ba-0be6-475c-b286-871e6a84d8f0.png)

**Details (please complete the following information):**
 - OS: Windows 10
 - Blender Version: 2.93
 - Addon Version: 1.0.0
 - Did you download a release or build the addon yourself: downloaded a release
 - Related Game: Counter-Strike: Source

**Comment by lasa01** [comment]
This will probably be quite difficult to fix, since it would require
automatic detection of the solids that are part of the 3d sky (and at that
point, might as well do the transformation automatically too). For a
workaround you can disable solid merging when importing, though this will
make the import slower.

**Comment by lasa01** [comment]
The default settings of the latest version do not have this issue, since solid merging is disabled.
