### ISSUE TITLE
Linux error: "LOADING FAILED: [Errno 2] No such file or directory: 'dotnet' " 

### ISSUE THREAD

**Issue by terrab0x** [lasa01/Plumber#136]
When importing a map, all of the props fail to load and give the error "LOADING FAILED: [Errno 2] No such file or directory: 'dotnet' "

1. Import a ctf_doublecross_d.vmf
3. See error

**Related files**
[ctf_doublecross_d.vmf.zip](https://github.com/lasa01/io_import_vmf/files/9255637/ctf_doublecross_d.vmf.zip)

**Logs**

[error.log](https://github.com/lasa01/io_import_vmf/files/9255642/error.log)

**Details (please complete the following information):**
 - OS: Arch Linux
 - Blender Version: 3.2
 - Addon Version: 0.6.9
 - Did you download a release or build the addon yourself: Downloaded a release
 - Related Game: Team Fortress 2

**Comment by lasa01** [comment]
Looks like you don't have .net core installed, which is required on linux like the readme says.

Though I would recommend you instead try the [latest beta version](https://github.com/lasa01/io_import_vmf/releases/tag/v1.0.0-beta3) which doesn't require .net core anymore.

**Comment by lasa01** [comment]
Closing since this is related to pre-1.0 versions.
