### ISSUE TITLE
File browser improvements | Plumber

### ISSUE THREAD

**Issue by JokanJan** [lasa01/Plumber#140]
**In these two months of use and found some optimization points :**

1、When the last character of the folder path has a slash, it does not open the corresponding folder
![Snipaste_2022-08-28_16-51-26](https://user-images.githubusercontent.com/46306699/187066203-7eaecd72-bd08-4d60-b78a-4edb433e512c.png)
![Snipaste_2022-08-28_16-51-18](https://user-images.githubusercontent.com/46306699/187066205-1199925a-6608-4110-a360-147061e542ab.png)

2、When you enter the full relative path of a file directly, can you invoke the import operation of the corresponding format?
![Snipaste_2022-08-28_16-51-52](https://user-images.githubusercontent.com/46306699/187066200-35bbc4ae-0abd-4673-ae1d-97279a5dee92.png)

3、Can we add a name filter (like blender's file browser) to quickly find the required file in a large number of files
![Snipaste_2022-08-28_16-57-30](https://user-images.githubusercontent.com/46306699/187066196-4a947966-17a6-46fa-a400-dc8d7bd58971.png)
![Snipaste_2022-08-28_16-54-29](https://user-images.githubusercontent.com/46306699/187066199-b55e0b64-b405-470d-9001-59af406f5ec1.png)

4、Can I record the path of the recently imported file folder or the folder collection function (like blender's file browser)?
![Snipaste_2022-08-28_17-25-37](https://user-images.githubusercontent.com/46306699/187067195-e7dc1147-8bb3-48d0-b7a6-025907c18ca6.png)

---

**I'm trying to use Plumber's browser to browse and import directly instead of the traditional way of unpacking to the hard drive and then importing. The file browser that allows you to view the vpk content without unpacking is very convenient, but it would be nice if the logic could be improved to be closer to Blender's own file browser ~ the current file browser is especially difficult to import multiple files in several different folders in a row.**

**Comment by lasa01** [comment]
Implemented in the latest beta release.
