### ISSUE TITLE
Doesn't work on M1/M2 Macs

### ISSUE THREAD

**Issue by temir-erd** [lasa01/Plumber#172]
**Describe the bug**
Adon does not activate, it gives errors

**To Reproduce**
1. Install plumber-v1.0.0-macOS.zip
2. Click the checkbox to activate the plugin

**Logs**
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/__init__.py", line 50, in register
    from . import addon
  File "/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/addon.py", line 4, in <module>
    from . import preferences, importer, tools, benchmark, version_str
  File "/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/preferences.py", line 1, in <module>
    from .plumber import discover_filesystems, FileSystem, filesystem_from_gameinfo
ImportError: dlopen(/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/plumber.abi3.so, 0x0002): tried: '/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/plumber.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/plumber.abi3.so' (no such file), '/Users/temir/Library/Application Support/Blender/3.6/scripts/addons/plumber/plumber.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))


```
**Screenshots**
<img width="717" alt="Снимок экрана 2023-10-25 в 19 05 14" src="https://github.com/lasa01/Plumber/assets/11175964/c38c5284-794d-4323-ad33-f36782acb4c9">

**Details (please complete the following information):**
 - OS: MacOs 14.0
 - Blender Version: 3.6.5
 - Addon Version: 1.0.0
 - Did you download a release or build the addon yourself: downloaded a release

**Comment by lasa01** [comment]
Unfortunately Macs with Apple M1 or M2 chips are not supported. The Mac version works for Intel Macs only.

It is possible that the compilation of the addon works on those Macs too, but I can't test it or publish a release since I don't have access to any Macs. There are instructions for manually building the addon, so if you have enough technical knowledge you can try that and see if it compiles.

**Comment by lasa01** [comment]
The latest release now contains ARM64 mac builds for M1/M2/M3/M4 etc., would appreciate if someone could test it!
