### ISSUE TITLE
Imported VMT not showing up

### ISSUE THREAD

**Issue by Filval387** [lasa01/Plumber#187]
**Describe the bug**
Whenever importing a VMT, it indicates that it was successful in the console, but the file is nowhere to be found inside of Blender

**To Reproduce**
1. Import a VMT file using file > import > plumber > Valve Material Type (Does the same with browse game files)
2. Set options to whatever
3. Choose any vmt file to import
4. The console shows that the file imported correctly, but it doesn't show up in the materials tab or anywhere in the file

**Expected behavior**
It should show up in the materials, but at the moment, it seems to process the VMT without actually saving it as a material.

**Logs**
```
[Plumber] [INFO] opening file system of game `PORTAL 2`...
[Plumber] [INFO] file system opened in 0.05 s
[Plumber] [INFO] detected local asset searh path `M:\Valve content\Portal 2 pak dir\root`
[Plumber] [INFO] importing vmt `M:\Valve content\Portal 2 pak dir\root\materials\wood\lobby_woodwall001a_trim.vmt`...
[Plumber] [INFO] vmt imported in 0.01 s
```
You can open the console with `Window -> Toggle System Console` on Windows.

**Details (please complete the following information):**
 - OS: Windows
 - Blender Version: 4.1
 - Addon Version: 1.0.2
 - Did you download a release or build the addon yourself: downloaded a release
 - Related Game: Portal 2

**Comment by Typur** [comment]
I have the same issue and i have not found a fix. Have you figured out how to fix it yet

**Comment by Filval387** [comment]
> I have the same issue and i have not found a fix. Have you figured out how to fix it yet

No, unfortunately... So far, all I've been doing is using an install of Blender 3.6.5, using the blender source tools addon to import materials and set them as fake user, save the blender file and then appending the materials from it to the file I want in Blender 4.2. It works, but it's not the most elegant solution and I really hope it gets fixed...

**Comment by lasa01** [comment]
That's a pretty bad bug, fixed in latest release
