### ISSUE TITLE
Some overlays fail to import

### ISSUE THREAD

**Issue by matty45** [lasa01/Plumber#23]
Hello, found another bug again, using the same vmf in issue #22

This time it seems that overlays are not scaled or in position correctly.

Hammer: 
![](https://i.imgur.com/VZSUSzt.jpg)

Blender:
![](https://i.imgur.com/fDRHBtW.jpg)

**Comment by lasa01** [comment]
This seems to be because the overlay in the picture fails to import, instead of incorrect transforms. I added better overlay import failure detection so they now print errors, but still haven't been able to fix the problem.

**Comment by lasa01** [comment]
Closing since this is related to pre-1.0 versions. You can reopen if this is still in the latest version.
